site_name: Locomotion Data Standardization
site_description: Standardized biomechanical datasets for reproducible research
site_url: https://locomotion-data-standardization.readthedocs.io/

repo_name: locomotion-data-standardization
repo_url: https://github.com/your-org/locomotion-data-standardization

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - tables
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  
  # For Users - Researchers analyzing data
  - For Users:
    - Overview: user_guide/docs/index.md
    - Getting Started: user_guide/docs/getting_started/index.md
    - Examples: user_guide/docs/examples/index.md
    - Tutorials:
      - Python: user_guide/docs/tutorials/python/getting_started_python.md
      - MATLAB: user_guide/docs/tutorials/matlab/getting_started_matlab.md
      - R Templates: users/tutorials/r/index.md
  
  # For Contributors - Adding new datasets
  - For Contributors:
    - Overview: contributing/index.md
    - Biomechanical Standard: reference/biomechanical_standard.md
    - Quick Reference: reference/quick_reference.md
  
  # For Maintainers - System development
  - For Maintainers:
    - Overview: maintainers/index.md
    - Scripts Cheat Sheet: maintainers/scripts_cheatsheet.md
    - Developer Guide: maintainers/developer_guide.md
    - Setup: maintainers/setup.md
    - Architecture: maintainers/architecture.md
    - Common Tasks: maintainers/tasks.md
    - Testing: maintainers/testing.md
    - Code Standards: maintainers/standards.md
    - Releases: maintainers/releases.md
    - Detailed Architecture:
      - Unit Tests: maintainers/15a_unit_tests.md
      - Integration Tests: maintainers/15b_integration_tests.md
      - Test Specifications: maintainers/18_test_specifications.md
  
  # Reference - Shared documentation
  - Reference:
    - Overview: reference/index.md
    - Core References:
      - Biomechanical Standard: reference/biomechanical_standard.md
      - Quick Reference: reference/quick_reference.md
      - Technical Specification: reference/standard_spec/standard_spec.md
      - Task Definitions: reference/standard_spec/task_definitions.md
    - Datasets:
      - Overview: reference/datasets_documentation/README.md
      - Validation Ranges: reference/datasets_documentation/validation_ranges.md
      - Available Datasets:
        - UMich 2021: reference/datasets_documentation/dataset_umich_2021.md
        - GTech 2023: reference/datasets_documentation/dataset_gtech_2023.md
        - AddBiomechanics: reference/datasets_documentation/dataset_addbiomechanics.md
      - Validation Reports: 
        - Overview: reference/datasets_documentation/validation_reports/index.md
        - UMich 2021: reference/datasets_documentation/validation_reports/umich_2021_phase_validation_report.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/locomotion-data-standardization

copyright: Copyright &copy; 2024 - Locomotion Data Standardization Project