site_name: LocoHub
site_description: LocoHub - Standardized biomechanical datasets for reproducible research
site_url: https://jmontp.github.io/LocoHub/

repo_name: jmontp/LocoHub
repo_url: https://github.com/jmontp/LocoHub

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - tables
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - LocoHub: index.md
  
  # For Users - Researchers analyzing data
  - For Users:
    - Overview: users/index.md
    - Tutorials:
      - Python:
        - Overview: users/tutorials/python/index.md
        - 1. Loading Data: users/tutorials/python/01_loading_data.md
        - 2. Data Filtering: users/tutorials/python/02_data_filtering.md
        - 3. Visualization: users/tutorials/python/03_visualization.md
        - 4. Cycle Analysis: users/tutorials/python/04_cycle_analysis.md
        - 5. Group Analysis: users/tutorials/python/05_group_analysis.md
        - 6. Publication Outputs: users/tutorials/python/06_publication_outputs.md
      - MATLAB:
        - Overview: users/tutorials/matlab/index.md
        - 1. Loading Data: users/tutorials/matlab/01_loading_data.md
        - 2. Data Filtering: users/tutorials/matlab/02_data_filtering.md
        - 3. Visualization: users/tutorials/matlab/03_visualization.md
        - 4. Cycle Analysis: users/tutorials/matlab/04_cycle_analysis.md
        - 5. Group Analysis: users/tutorials/matlab/05_group_analysis.md
        - 6. Publication Outputs: users/tutorials/matlab/06_publication_outputs.md
        - Advanced Guides:
          - Biomechanics Visualization: users/tutorials/matlab/biomechanics_visualization_guide.md
      - R:
        - Using Libraries: users/tutorials/r/index.md
        - Using Raw Data: users/tutorials/r/raw_data_guide.md
    - API Reference:
      - Overview: users/api/api-index.md
      - Python API: users/api/locomotion-data-api.md
      - MATLAB API: users/api/matlab-api.md
      - R API: users/api/r-api.md
      - Validation API: users/api/validation-api.md
  
  # For Contributors - Adding new datasets
  - For Contributors:
    - Overview: contributing/index.md
    - Conversion Guide: contributing/conversion_guide.md
    - Validation Reference: contributing/validation_reference.md
    - Tools Reference: contributing/tools_reference.md
    - Biomechanical Standard: reference/biomechanical_standard.md
    - Quick Reference: reference/quick_reference.md
  
  # For Maintainers - System development
  - For Maintainers:
    - Overview: maintainers/index.md
    - Scripts Cheat Sheet: maintainers/scripts_cheatsheet.md
    - Developer Guide: maintainers/developer_guide.md
    - Setup: maintainers/setup.md
    - Architecture: maintainers/architecture.md
    - Common Tasks: maintainers/tasks.md
    - Testing: maintainers/testing.md
    - Code Standards: maintainers/standards.md
    - Releases: maintainers/releases.md
    - Detailed Architecture:
      - Unit Tests: maintainers/15a_unit_tests.md
      - Integration Tests: maintainers/15b_integration_tests.md
      - Test Specifications: maintainers/18_test_specifications.md
  
  # Reference - Shared documentation
  - Reference:
    - Overview: reference/index.md
    - Core References:
      - Biomechanical Standard: reference/biomechanical_standard.md
      - Quick Reference: reference/quick_reference.md
      - Technical Specification: reference/standard_spec/standard_spec.md
      - Task Definitions: reference/standard_spec/task_definitions.md
    - Datasets:
      - Overview: reference/datasets_documentation/README.md
      - Validation Ranges: reference/datasets_documentation/validation_ranges.md
      - Dataset Comparison: reference/datasets_documentation/dataset_comparison.md
      - Available Datasets:
        - Gtech 2021: reference/datasets_documentation/dataset_gtech_2021.md
        - UMich 2021: reference/datasets_documentation/dataset_umich_2021.md
        - GTech 2023: reference/datasets_documentation/dataset_gtech_2023.md
        - AddBiomechanics: reference/datasets_documentation/dataset_addbiomechanics.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/locomotion-data-standardization

copyright: Copyright &copy; 2024 - LocoHub Project