site_name: LocoHub
site_description: LocoHub - Standardized biomechanical datasets for reproducible research
site_url: https://jmontp.github.io/LocoHub/

repo_name: jmontp/LocoHub
repo_url: https://github.com/jmontp/LocoHub

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path:
        - docs/users/tutorials
        - docs
      check_paths: true
  - tables
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - LocoHub: index.md
  - Tutorials: tutorials/index.md
  - Contribute:
      - Overview: contributing/index.md
      - Standard Operating Procedures: contributing/standard_operating_procedures.md
      - Tool Tutorials: contributing/tool_tutorials.md
  - Maintain:
      - Overview: maintainers/index.md
      - Website Flow: maintainers/website_management_flow.md
  - Reference: reference/index.md
  - API: api/api-index.md
  - Datasets: datasets/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmontp/LocoHub

copyright: Copyright &copy; 2024 - LocoHub Project
