agent_name: integration_agent
agent_type: integration_agent
communication_settings:
  acknowledgment_required: true
  delivery_guarantee: at_least_once
  max_message_size: 10485760
  message_timeout_seconds: 300
  retry_count: 3
  transport_protocol: synchronous
environment_variables:
  AGENT_TYPE: INTEGRATION_AGENT
  CONFLICT_RESOLUTION_AUTO: 'false'
  INTEGRATION_TIMEOUT: '600'
  LOG_LEVEL: INFO
  MONITORING_ENABLED: 'true'
  QUALITY_GATE_STRICT: 'true'
  WORKSPACE_ISOLATION: 'true'
monitoring_settings:
  alert_thresholds:
    completion_delay_hours: 24.0
    error_rate_maximum: 0.05
    quality_score_minimum: 0.8
  metrics_collection_enabled: true
  performance_benchmarking: true
  progress_update_interval_seconds: 900
  quality_tracking_enabled: true
performance_settings: {}
security_settings:
  access_control_enabled: true
  allowed_agents: []
  audit_logging: true
  message_encryption: false
  secure_communication: false
  workspace_isolation: true
workspace_path: /mnt/c/Users/jmontp/Documents/workspace/locomotion-data-standardization/agent_workspaces/integration_agent
