# MATLAB Analysis Deployment for Kubernetes
#
# Created: 2025-06-20 with user permission
# Purpose: Kubernetes deployment for MATLAB-based locomotion data analysis
#
# Intent: Deploy scalable MATLAB analysis environment with proper resource
# allocation, health monitoring, and integration with monitoring systems.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matlab-analysis
  namespace: locomotion-analysis
  labels:
    app: matlab-analysis
    component: compute
    language: matlab
    tier: analysis
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: matlab-analysis
  template:
    metadata:
      labels:
        app: matlab-analysis
        component: compute
        language: matlab
        tier: analysis
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: locomotion-analysis-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      
      containers:
      - name: matlab-analysis
        image: locomotion/matlab-dev:latest
        imagePullPolicy: Always
        
        ports:
        - containerPort: 9091
          name: metrics
          protocol: TCP
        - containerPort: 8080
          name: health
          protocol: TCP
        
        env:
        - name: MATLAB_PREFDIR
          value: "/tmp/.matlab"
        - name: MLM_LICENSE_FILE
          valueFrom:
            secretKeyRef:
              name: matlab-license
              key: license-server
        - name: LOCOMOTION_LIB
          value: "/opt/locomotion"
        - name: MCR_CACHE_ROOT
          value: "/tmp/mcr_cache"
        - name: PROMETHEUS_METRICS_PORT
          value: "9091"
        
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            ephemeral-storage: "10Gi"
          limits:
            memory: "8Gi"
            cpu: "4"
            ephemeral-storage: "20Gi"
        
        volumeMounts:
        - name: data-storage
          mountPath: /opt/locomotion/data
          readOnly: true
        - name: output-storage
          mountPath: /opt/locomotion/output
        - name: logs-storage
          mountPath: /opt/locomotion/logs
        - name: tmp-storage
          mountPath: /tmp
        - name: matlab-config
          mountPath: /opt/locomotion/config
          readOnly: true
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "matlab -batch 'fprintf(\"Graceful shutdown initiated\\n\"); exit(0)'"]
      
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: locomotion-data-pvc
      - name: output-storage
        persistentVolumeClaim:
          claimName: locomotion-output-pvc
      - name: logs-storage
        persistentVolumeClaim:
          claimName: locomotion-logs-pvc
      - name: tmp-storage
        emptyDir:
          sizeLimit: "5Gi"
      - name: matlab-config
        configMap:
          name: matlab-config
      
      nodeSelector:
        workload-type: "compute-intensive"
      
      tolerations:
      - key: "matlab-license"
        operator: "Equal"
        value: "required"
        effect: "NoSchedule"
      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["matlab-analysis"]
              topologyKey: kubernetes.io/hostname

---
# Service for MATLAB analysis pods
apiVersion: v1
kind: Service
metadata:
  name: matlab-analysis-service
  namespace: locomotion-analysis
  labels:
    app: matlab-analysis
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
spec:
  type: ClusterIP
  ports:
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: metrics
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: health
  selector:
    app: matlab-analysis

---
# Horizontal Pod Autoscaler for MATLAB analysis
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: matlab-analysis-hpa
  namespace: locomotion-analysis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matlab-analysis
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: dataset_processing_queue_length
      target:
        type: AverageValue
        averageValue: "5"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Min
      policies:
      - type: Percent
        value: 50
        periodSeconds: 120

---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: matlab-analysis-pdb
  namespace: locomotion-analysis
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: matlab-analysis