version: '1.0'
generated: '2025-08-03 11:07:47'
source: Migrated from validation_expectations_kinetic.md
migration_date: '2025-08-03 11:07:47'
description: Kinetic validation ranges for forces and moments
source_dataset: umich_2021_phase.parquet
method: 95th percentile
tasks:
  decline_walking:
    phases:
      '0':
        ankle_adduction_moment_contra:
          min: -0.094
          max: 0.301
        ankle_adduction_moment_ipsi:
          min: -0.056
          max: 0.024
        ankle_flexion_moment_contra:
          min: -1.656
          max: -0.761
        ankle_flexion_moment_ipsi:
          min: -0.067
          max: 0.114
        ankle_rotation_moment_contra:
          min: -0.022
          max: 0.191
        ankle_rotation_moment_ipsi:
          min: -0.18
          max: 0.037
        hip_adduction_moment_contra:
          min: 0.143
          max: 0.855
        hip_adduction_moment_ipsi:
          min: -0.155
          max: 0.176
        hip_flexion_moment_contra:
          min: 0.203
          max: 1.1
        hip_flexion_moment_ipsi:
          min: -0.624
          max: -0.053
        hip_rotation_moment_contra:
          min: -0.212
          max: 0.105
        hip_rotation_moment_ipsi:
          min: -0.174
          max: 0.057
        knee_adduction_moment_contra:
          min: -0.01
          max: 0.539
        knee_adduction_moment_ipsi:
          min: -0.083
          max: 0.112
        knee_flexion_moment_contra:
          min: -0.792
          max: 0.198
        knee_flexion_moment_ipsi:
          min: 0.041
          max: 0.363
        knee_rotation_moment_contra:
          min: -0.036
          max: 0.187
        knee_rotation_moment_ipsi:
          min: -0.188
          max: 0.038
      '25':
        ankle_adduction_moment_contra:
          min: -0.0
          max: 0.185
        ankle_adduction_moment_ipsi:
          min: -0.107
          max: 0.233
        ankle_flexion_moment_contra:
          min: -0.027
          max: 0.067
        ankle_flexion_moment_ipsi:
          min: -1.464
          max: -0.298
        ankle_rotation_moment_contra:
          min: -0.148
          max: 0.02
        ankle_rotation_moment_ipsi:
          min: -0.295
          max: 0.115
        hip_adduction_moment_contra:
          min: -0.045
          max: 0.22
        hip_adduction_moment_ipsi:
          min: 0.364
          max: 0.958
        hip_flexion_moment_contra:
          min: -0.239
          max: 0.157
        hip_flexion_moment_ipsi:
          min: -0.283
          max: 0.515
        hip_rotation_moment_contra:
          min: -0.353
          max: 0.013
        hip_rotation_moment_ipsi:
          min: -0.435
          max: 0.043
        knee_adduction_moment_contra:
          min: -0.022
          max: 0.314
        knee_adduction_moment_ipsi:
          min: 0.062
          max: 0.619
        knee_flexion_moment_contra:
          min: -0.112
          max: 0.109
        knee_flexion_moment_ipsi:
          min: -0.653
          max: 0.252
        knee_rotation_moment_contra:
          min: -0.125
          max: 0.02
        knee_rotation_moment_ipsi:
          min: -0.268
          max: 0.138
      '50':
        ankle_adduction_moment_contra:
          min: -0.056
          max: 0.024
        ankle_adduction_moment_ipsi:
          min: -0.094
          max: 0.301
        ankle_flexion_moment_contra:
          min: -0.067
          max: 0.114
        ankle_flexion_moment_ipsi:
          min: -1.656
          max: -0.761
        ankle_rotation_moment_contra:
          min: -0.18
          max: 0.037
        ankle_rotation_moment_ipsi:
          min: -0.022
          max: 0.191
        hip_adduction_moment_contra:
          min: -0.155
          max: 0.176
        hip_adduction_moment_ipsi:
          min: 0.143
          max: 0.855
        hip_flexion_moment_contra:
          min: -0.624
          max: -0.053
        hip_flexion_moment_ipsi:
          min: 0.203
          max: 1.1
        hip_rotation_moment_contra:
          min: -0.174
          max: 0.057
        hip_rotation_moment_ipsi:
          min: -0.212
          max: 0.105
        knee_adduction_moment_contra:
          min: -0.083
          max: 0.112
        knee_adduction_moment_ipsi:
          min: -0.01
          max: 0.539
        knee_flexion_moment_contra:
          min: 0.041
          max: 0.363
        knee_flexion_moment_ipsi:
          min: -0.792
          max: 0.198
        knee_rotation_moment_contra:
          min: -0.188
          max: 0.038
        knee_rotation_moment_ipsi:
          min: -0.036
          max: 0.187
      '75':
        ankle_adduction_moment_contra:
          min: -0.107
          max: 0.233
        ankle_adduction_moment_ipsi:
          min: -0.0
          max: 0.185
        ankle_flexion_moment_contra:
          min: -1.464
          max: -0.298
        ankle_flexion_moment_ipsi:
          min: -0.027
          max: 0.067
        ankle_rotation_moment_contra:
          min: -0.295
          max: 0.115
        ankle_rotation_moment_ipsi:
          min: -0.148
          max: 0.02
        hip_adduction_moment_contra:
          min: 0.364
          max: 0.958
        hip_adduction_moment_ipsi:
          min: -0.045
          max: 0.22
        hip_flexion_moment_contra:
          min: -0.283
          max: 0.515
        hip_flexion_moment_ipsi:
          min: -0.239
          max: 0.157
        hip_rotation_moment_contra:
          min: -0.435
          max: 0.043
        hip_rotation_moment_ipsi:
          min: -0.353
          max: 0.013
        knee_adduction_moment_contra:
          min: 0.062
          max: 0.619
        knee_adduction_moment_ipsi:
          min: -0.022
          max: 0.314
        knee_flexion_moment_contra:
          min: -0.653
          max: 0.252
        knee_flexion_moment_ipsi:
          min: -0.112
          max: 0.109
        knee_rotation_moment_contra:
          min: -0.268
          max: 0.138
        knee_rotation_moment_ipsi:
          min: -0.125
          max: 0.02
  incline_walking:
    phases:
      '0':
        ankle_adduction_moment_contra:
          min: .nan
          max: .nan
        ankle_adduction_moment_ipsi:
          min: .nan
          max: .nan
        ankle_flexion_moment_contra:
          min: .nan
          max: .nan
        ankle_flexion_moment_ipsi:
          min: .nan
          max: .nan
        ankle_rotation_moment_contra:
          min: .nan
          max: .nan
        ankle_rotation_moment_ipsi:
          min: .nan
          max: .nan
        hip_adduction_moment_contra:
          min: .nan
          max: .nan
        hip_adduction_moment_ipsi:
          min: .nan
          max: .nan
        hip_flexion_moment_contra:
          min: .nan
          max: .nan
        hip_flexion_moment_ipsi:
          min: .nan
          max: .nan
        hip_rotation_moment_contra:
          min: .nan
          max: .nan
        hip_rotation_moment_ipsi:
          min: .nan
          max: .nan
        knee_adduction_moment_contra:
          min: .nan
          max: .nan
        knee_adduction_moment_ipsi:
          min: .nan
          max: .nan
        knee_flexion_moment_contra:
          min: .nan
          max: .nan
        knee_flexion_moment_ipsi:
          min: .nan
          max: .nan
        knee_rotation_moment_contra:
          min: .nan
          max: .nan
        knee_rotation_moment_ipsi:
          min: .nan
          max: .nan
      '25':
        ankle_adduction_moment_contra:
          min: .nan
          max: .nan
        ankle_adduction_moment_ipsi:
          min: .nan
          max: .nan
        ankle_flexion_moment_contra:
          min: .nan
          max: .nan
        ankle_flexion_moment_ipsi:
          min: .nan
          max: .nan
        ankle_rotation_moment_contra:
          min: .nan
          max: .nan
        ankle_rotation_moment_ipsi:
          min: .nan
          max: .nan
        hip_adduction_moment_contra:
          min: .nan
          max: .nan
        hip_adduction_moment_ipsi:
          min: .nan
          max: .nan
        hip_flexion_moment_contra:
          min: .nan
          max: .nan
        hip_flexion_moment_ipsi:
          min: .nan
          max: .nan
        hip_rotation_moment_contra:
          min: .nan
          max: .nan
        hip_rotation_moment_ipsi:
          min: .nan
          max: .nan
        knee_adduction_moment_contra:
          min: .nan
          max: .nan
        knee_adduction_moment_ipsi:
          min: .nan
          max: .nan
        knee_flexion_moment_contra:
          min: .nan
          max: .nan
        knee_flexion_moment_ipsi:
          min: .nan
          max: .nan
        knee_rotation_moment_contra:
          min: .nan
          max: .nan
        knee_rotation_moment_ipsi:
          min: .nan
          max: .nan
      '50':
        ankle_adduction_moment_contra:
          min: .nan
          max: .nan
        ankle_adduction_moment_ipsi:
          min: .nan
          max: .nan
        ankle_flexion_moment_contra:
          min: .nan
          max: .nan
        ankle_flexion_moment_ipsi:
          min: .nan
          max: .nan
        ankle_rotation_moment_contra:
          min: .nan
          max: .nan
        ankle_rotation_moment_ipsi:
          min: .nan
          max: .nan
        hip_adduction_moment_contra:
          min: .nan
          max: .nan
        hip_adduction_moment_ipsi:
          min: .nan
          max: .nan
        hip_flexion_moment_contra:
          min: .nan
          max: .nan
        hip_flexion_moment_ipsi:
          min: .nan
          max: .nan
        hip_rotation_moment_contra:
          min: .nan
          max: .nan
        hip_rotation_moment_ipsi:
          min: .nan
          max: .nan
        knee_adduction_moment_contra:
          min: .nan
          max: .nan
        knee_adduction_moment_ipsi:
          min: .nan
          max: .nan
        knee_flexion_moment_contra:
          min: .nan
          max: .nan
        knee_flexion_moment_ipsi:
          min: .nan
          max: .nan
        knee_rotation_moment_contra:
          min: .nan
          max: .nan
        knee_rotation_moment_ipsi:
          min: .nan
          max: .nan
      '75':
        ankle_adduction_moment_contra:
          min: .nan
          max: .nan
        ankle_adduction_moment_ipsi:
          min: .nan
          max: .nan
        ankle_flexion_moment_contra:
          min: .nan
          max: .nan
        ankle_flexion_moment_ipsi:
          min: .nan
          max: .nan
        ankle_rotation_moment_contra:
          min: .nan
          max: .nan
        ankle_rotation_moment_ipsi:
          min: .nan
          max: .nan
        hip_adduction_moment_contra:
          min: .nan
          max: .nan
        hip_adduction_moment_ipsi:
          min: .nan
          max: .nan
        hip_flexion_moment_contra:
          min: .nan
          max: .nan
        hip_flexion_moment_ipsi:
          min: .nan
          max: .nan
        hip_rotation_moment_contra:
          min: .nan
          max: .nan
        hip_rotation_moment_ipsi:
          min: .nan
          max: .nan
        knee_adduction_moment_contra:
          min: .nan
          max: .nan
        knee_adduction_moment_ipsi:
          min: .nan
          max: .nan
        knee_flexion_moment_contra:
          min: .nan
          max: .nan
        knee_flexion_moment_ipsi:
          min: .nan
          max: .nan
        knee_rotation_moment_contra:
          min: .nan
          max: .nan
        knee_rotation_moment_ipsi:
          min: .nan
          max: .nan
  level_walking:
    phases:
      '0':
        ankle_adduction_moment_contra:
          min: -0.09
          max: 0.257
        ankle_adduction_moment_ipsi:
          min: -0.018
          max: 0.055
        ankle_flexion_moment_contra:
          min: -1.916
          max: -0.99
        ankle_flexion_moment_ipsi:
          min: -0.034
          max: 0.067
        ankle_rotation_moment_contra:
          min: -0.015
          max: 0.171
        ankle_rotation_moment_ipsi:
          min: -0.018
          max: 0.017
        hip_adduction_moment_contra:
          min: 0.144
          max: 0.826
        hip_adduction_moment_ipsi:
          min: -0.188
          max: 0.148
        hip_flexion_moment_contra:
          min: 0.096
          max: 0.977
        hip_flexion_moment_ipsi:
          min: -0.773
          max: -0.113
        hip_rotation_moment_contra:
          min: 0.011
          max: 0.153
        hip_rotation_moment_ipsi:
          min: -0.034
          max: 0.054
        knee_adduction_moment_contra:
          min: -0.184
          max: 0.374
        knee_adduction_moment_ipsi:
          min: -0.078
          max: 0.086
        knee_flexion_moment_contra:
          min: 0.007
          max: 0.512
        knee_flexion_moment_ipsi:
          min: 0.077
          max: 0.387
        knee_rotation_moment_contra:
          min: -0.035
          max: 0.196
        knee_rotation_moment_ipsi:
          min: -0.017
          max: 0.018
      '25':
        ankle_adduction_moment_contra:
          min: -0.0
          max: 0.0
        ankle_adduction_moment_ipsi:
          min: -0.164
          max: 0.192
        ankle_flexion_moment_contra:
          min: 0.0
          max: 0.031
        ankle_flexion_moment_ipsi:
          min: -1.206
          max: -0.251
        ankle_rotation_moment_contra:
          min: -0.011
          max: 0.018
        ankle_rotation_moment_ipsi:
          min: -0.016
          max: 0.127
        hip_adduction_moment_contra:
          min: -0.06
          max: 0.153
        hip_adduction_moment_ipsi:
          min: 0.324
          max: 0.872
        hip_flexion_moment_contra:
          min: -0.064
          max: 0.166
        hip_flexion_moment_ipsi:
          min: -0.422
          max: 0.248
        hip_rotation_moment_contra:
          min: -0.041
          max: 0.011
        hip_rotation_moment_ipsi:
          min: -0.031
          max: 0.085
        knee_adduction_moment_contra:
          min: -0.029
          max: 0.058
        knee_adduction_moment_ipsi:
          min: -0.001
          max: 0.522
        knee_flexion_moment_contra:
          min: -0.116
          max: -0.0
        knee_flexion_moment_ipsi:
          min: -0.208
          max: 0.445
        knee_rotation_moment_contra:
          min: -0.011
          max: 0.019
        knee_rotation_moment_ipsi:
          min: -0.015
          max: 0.148
      '50':
        ankle_adduction_moment_contra:
          min: -0.018
          max: 0.055
        ankle_adduction_moment_ipsi:
          min: -0.09
          max: 0.257
        ankle_flexion_moment_contra:
          min: -0.034
          max: 0.067
        ankle_flexion_moment_ipsi:
          min: -1.916
          max: -0.99
        ankle_rotation_moment_contra:
          min: -0.018
          max: 0.017
        ankle_rotation_moment_ipsi:
          min: -0.015
          max: 0.171
        hip_adduction_moment_contra:
          min: -0.188
          max: 0.148
        hip_adduction_moment_ipsi:
          min: 0.144
          max: 0.826
        hip_flexion_moment_contra:
          min: -0.773
          max: -0.113
        hip_flexion_moment_ipsi:
          min: 0.096
          max: 0.977
        hip_rotation_moment_contra:
          min: -0.034
          max: 0.054
        hip_rotation_moment_ipsi:
          min: 0.011
          max: 0.153
        knee_adduction_moment_contra:
          min: -0.078
          max: 0.086
        knee_adduction_moment_ipsi:
          min: -0.184
          max: 0.374
        knee_flexion_moment_contra:
          min: 0.077
          max: 0.387
        knee_flexion_moment_ipsi:
          min: 0.007
          max: 0.512
        knee_rotation_moment_contra:
          min: -0.017
          max: 0.018
        knee_rotation_moment_ipsi:
          min: -0.035
          max: 0.196
      '75':
        ankle_adduction_moment_contra:
          min: -0.164
          max: 0.192
        ankle_adduction_moment_ipsi:
          min: -0.0
          max: 0.0
        ankle_flexion_moment_contra:
          min: -1.206
          max: -0.251
        ankle_flexion_moment_ipsi:
          min: 0.0
          max: 0.031
        ankle_rotation_moment_contra:
          min: -0.016
          max: 0.127
        ankle_rotation_moment_ipsi:
          min: -0.011
          max: 0.018
        hip_adduction_moment_contra:
          min: 0.324
          max: 0.872
        hip_adduction_moment_ipsi:
          min: -0.06
          max: 0.153
        hip_flexion_moment_contra:
          min: -0.422
          max: 0.248
        hip_flexion_moment_ipsi:
          min: -0.064
          max: 0.166
        hip_rotation_moment_contra:
          min: -0.031
          max: 0.085
        hip_rotation_moment_ipsi:
          min: -0.041
          max: 0.011
        knee_adduction_moment_contra:
          min: -0.001
          max: 0.522
        knee_adduction_moment_ipsi:
          min: -0.029
          max: 0.058
        knee_flexion_moment_contra:
          min: -0.208
          max: 0.445
        knee_flexion_moment_ipsi:
          min: -0.116
          max: -0.0
        knee_rotation_moment_contra:
          min: -0.015
          max: 0.148
        knee_rotation_moment_ipsi:
          min: -0.011
          max: 0.019
