communication_enabled: true
framework_version: 1.0.0
logging_level: INFO
max_concurrent_agents: 3
message_retention_days: 30
metrics_retention_days: 90
monitoring_enabled: true
security_enabled: true
workspace_base_path: /mnt/c/Users/jmontp/Documents/workspace/locomotion-data-standardization/agent_workspaces/shared/agent_workspaces
